Enable an option for setting the repo trunk branch
HaywardMorihara/gh-tidy pull request #47
Opened 2024-02-09 18:52 UTC by spoilsportmotors

This was the simplest thing I could think of to let someone specify the trunk branch.  If it doesn't exist, it'll just use the defaults as it did before.

Hopefully addresses https://github.com/HaywardMorihara/gh-tidy/issues/46

2024-02-10 03:16 UTC, HaywardMorihara requested changes
Awesome, thank you! A few requests/suggestions

2024-02-10 03:16 UTC, HaywardMorihara commented on gh-tidy
> +    red "No trunk branch found; specify one with the --trunk <branch-name> flag"
Nice, but I think we'll need to add a `return` statement after line [111](https://github.com/HaywardMorihara/gh-tidy/pull/47/files#diff-cb00acde26888e35e8b9cfd5016cc5107345ba46f582bf6ddb28ba7204697fddR111) for this to work properly, right?

2024-02-10 03:16 UTC, HaywardMorihara commented on gh-tidy
>  function set_master_or_main() {
```suggestion
function set_trunk_branch() {
```
mind adjusting this while you're at it?

2024-02-10 03:16 UTC, HaywardMorihara commented on README.md
> +If your repo doesn't _have_ a master/main branch, you can specify your trunk branch with the `--trunk <branchname>` parameter
Thanks for adding the documentation about it!

2024-02-10 03:16 UTC, HaywardMorihara commented on gh-tidy
> +TRUNK_BRANCH=''
nit:
```suggestion
TRUNK_BRANCH_PARAM=''
```
just to help further differentiate it from `trunk_branch` and make it clear where this is expected to come from

2024-02-12 01:14 UTC, spoilsportmotors commented
Updated -- I didn't touch [the other](https://github.com/HaywardMorihara/gh-tidy/issues/43) issue, though. I need to think on that some more before I'd dare poke at that bear.

2024-02-13 00:32 UTC, HaywardMorihara approved these changes
Beauitful, thank you very much!

2024-02-17 03:27 UTC, merged